### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by changchichung** [OSSII/oxool-community#9]
在執行這一段指令時，發生錯誤
```
編譯 oxool-community 與執行

透過 autotool 設定專案
./autogen.sh

編譯
make -j4
```
error
```
npm WARN notsup Unsupported engine for shrinkpack@1.0.0-alpha: wanted: {"node":">=4.0","npm":"<=5.8.0"} (current: {"node":"10.23.2","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: shrinkpack@1.0.0-alpha

added 572 packages from 365 contributors and audited 572 packages in 20.034s

3 packages are looking for funding
  run `npm fund` for details

found 58 vulnerabilities (34 low, 9 moderate, 15 high)
  run `npm audit fix` to fix them, or `npm audit` for details
make[3]: Leaving directory '/home/changch/git/oxool-community/loleaflet'
make[3]: Entering directory '/home/changch/git/oxool-community/loleaflet'
Traceback (most recent call last):
Traceback (most recent call last):
  File "./util/po2json.py", line 9, in <module>
  File "./util/po2json.py", line 9, in <module>
    import polib
    import polib
ImportErrorImportError: : No module named polibNo module named polib

Traceback (most recent call last):
  File "./util/po2json.py", line 9, in <module>
    import polib
ImportError: No module named polib
Traceback (most recent call last):
  File "./util/po2json.py", line 9, in <module>
    import polib
ImportError: No module named polib
Makefile:758: recipe for target 'dist/l10n/ui-jv.json' failed
make[3]: *** [dist/l10n/ui-jv.json] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:758: recipe for target 'dist/l10n/ui-en_GB.json' failed
make[3]: *** [dist/l10n/ui-en_GB.json] Error 1
Makefile:758: recipe for target 'dist/l10n/help-ts.json' failed
make[3]: *** [dist/l10n/help-ts.json] Error 1
Makefile:758: recipe for target 'dist/l10n/ui-ab.json' failed
make[3]: *** [dist/l10n/ui-ab.json] Error 1
make[3]: Leaving directory '/home/changch/git/oxool-community/loleaflet'
Makefile:613: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 2
make[2]: Leaving directory '/home/changch/git/oxool-community/loleaflet'
Makefile:1943: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/changch/git/oxool-community'
Makefile:834: recipe for target 'all' failed
make: *** [all] Error 2
```

OS
```
2021-02-04 10:27:25 [changch@hqdc034 oxool-community]$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by changchichung** [comment]
手動安裝 polib
```
sudo pip3 install polib
確認polib 版本
2021-02-04 10:32:22 [changch@hqdc034 oxool-community]$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polib
>>> print(polib.__version__)
1.1.0
>>> 
```
再次 make 還是出錯
```
2021-02-04 10:33:55 [changch@hqdc034 oxool-community]$ make -j4
make  all-recursive
make[1]: Entering directory '/home/changch/git/oxool-community'
Making all in bundled/include/LibreOfficeKit
make[2]: Entering directory '/home/changch/git/oxool-community/bundled/include/LibreOfficeKit'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/changch/git/oxool-community/bundled/include/LibreOfficeKit'
Making all in src/include
make[2]: Entering directory '/home/changch/git/oxool-community/src/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/changch/git/oxool-community/src/include'
Making all in common
make[2]: Entering directory '/home/changch/git/oxool-community/common'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/changch/git/oxool-community/common'
Making all in net
make[2]: Entering directory '/home/changch/git/oxool-community/net'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/changch/git/oxool-community/net'
Making all in src/lib
make[2]: Entering directory '/home/changch/git/oxool-community/src/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/changch/git/oxool-community/src/lib'
Making all in wsd
make[2]: Entering directory '/home/changch/git/oxool-community/wsd'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/changch/git/oxool-community/wsd'
Making all in kit
make[2]: Entering directory '/home/changch/git/oxool-community/kit'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/changch/git/oxool-community/kit'
Making all in loleaflet
make[2]: Entering directory '/home/changch/git/oxool-community/loleaflet'
make[3]: Entering directory '/home/changch/git/oxool-community/loleaflet'
make[3]: 'node_modules' is up to date.
make[3]: Leaving directory '/home/changch/git/oxool-community/loleaflet'
make[3]: Entering directory '/home/changch/git/oxool-community/loleaflet'
Traceback (most recent call last):
  File "./util/po2json.py", line 9, in <module>
    import polib
ImportError: No module named polib
Traceback (most recent call last):
Traceback (most recent call last):
  File "./util/po2json.py", line 9, in <module>
    import polib
  File "./util/po2json.py", line 9, in <module>
    import polib
ImportError: No module named polib
ImportError: No module named polib
Makefile:758: recipe for target 'dist/l10n/ui-jv.json' failed
make[3]: *** [dist/l10n/ui-jv.json] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:758: recipe for target 'dist/l10n/ui-en_GB.json' failed
make[3]: *** [dist/l10n/ui-en_GB.json] Error 1
Makefile:758: recipe for target 'dist/l10n/ui-ab.json' failed
make[3]: *** [dist/l10n/ui-ab.json] Error 1
Traceback (most recent call last):
  File "./util/po2json.py", line 9, in <module>
    import polib
ImportError: No module named polib
Makefile:758: recipe for target 'dist/l10n/help-ts.json' failed
make[3]: *** [dist/l10n/help-ts.json] Error 1
make[3]: Leaving directory '/home/changch/git/oxool-community/loleaflet'
Makefile:613: recipe for target 'all-local' failed
make[2]: *** [all-local] Error 2
make[2]: Leaving directory '/home/changch/git/oxool-community/loleaflet'
Makefile:1943: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/changch/git/oxool-community'
Makefile:834: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by s8321414** [comment]
我們目前的編譯環境是使用 Node.js 10 與 python 2，您裝的版本都太新了，麻煩降版 :smiley:
